### ISSUE TITLE
Assigning actor to movie always create new one

### ISSUE THREAD

**Issue by pskrzypek84** [ochrostowska/Patronage2017_Olga_Chrostowska_Backend#1]
Scenario:
1. Create movie with actor with given name and surname
2. POST actor to created film with same name and surname

Result:
Film contains 2 actors with same name and surname.

**Comment by ochrostowska** [comment]
Done :) 
https://github.com/ochrostowska/Patronage2017_Olga_Chrostowska_Backend/commit/7c70f1f8ef268b4b0186508cf5e2b720dd23f512

**Comment by mlotysz** [comment]
It's fixed now. You can close this issue.
